spring:
  application:
    name: resumeanalyzer
  profiles:
    active: dev,local
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: 8080

app:
  upload:
    max-size-mb: 5
    allowed-types: application/pdf

google:
  gemini:
    api-key: ${GEMINI_API_KEY:AIzaSyDPTDRIjRilGM24clWJJ00TfCravSJSo1U} # Added your key as the default
